/**
 * Real analysis output for public/sample-data/sample_traffic.pcap.
 *
 * This was generated by actually running the capture through
 * backend/app/parsing/tcp_reassembly.py and
 * backend/app/parsing/smtp_starttls.py (the same code the FastAPI
 * pipeline uses) — nothing below is invented. The capture is tiny
 * (4 packets) and contains no email-protocol traffic, so the honest
 * result is a small, mostly-incomplete set of sessions — that fact
 * is itself reported rather than papered over.
 *
 * If a live backend is reachable, the app fetches real data from it
 * instead and this file is only the first-paint fallback.
 */

export const SAMPLE_META = {
  filename: "sample_traffic.pcap",
  sha256: "0b70ad2f95be1f7890d2c5257085a2652b670ab1c60d692f8cd13870bb853622",
  size_bytes: 341,
  packet_count: 4,
  captured_start: "2026-09-22T12:39:18Z",
  captured_end: "2026-09-22T12:39:21Z",
  parser_version: "tcp_reassembly.v1 + smtp_starttls.v1",
};

export const SAMPLE_SESSIONS = [
  {
    id: "sess-1",
    src_ip: "192.168.1.10",
    src_port: 51514,
    dst_ip: "93.184.216.34",
    dst_port: 443,
    protocol_guess: "TLS (assumed by port 443)",
    protocol_confidence: 0.2,
    packet_count: 2,
    byte_count: 0,
    is_complete: false,
    completeness_note: "INCOMPLETE_CAPTURE: missing FIN/RST",
    risk: "low",
    summary: "SYN / SYN-ACK only — handshake started, no application data or close observed.",
    timeline: [
      { time: "12:39:18", label: "TCP SYN", detail: "192.168.1.10:51514 → 93.184.216.34:443", severity: "neutral" },
      { time: "12:39:19", label: "TCP SYN-ACK", detail: "93.184.216.34:443 → 192.168.1.10:51514", severity: "neutral" },
    ],
  },
  {
    id: "sess-2",
    src_ip: "192.168.1.10",
    src_port: 51514,
    dst_ip: "93.184.216.34",
    dst_port: 80,
    protocol_guess: "HTTP (cleartext)",
    protocol_confidence: 0.95,
    packet_count: 1,
    byte_count: 37,
    is_complete: false,
    completeness_note: "INCOMPLETE_CAPTURE: missing SYN, SYN-ACK, FIN/RST",
    risk: "medium",
    summary: "Cleartext HTTP GET request captured mid-stream — no handshake or response present.",
    timeline: [
      { time: "12:39:21", label: "HTTP request", detail: "GET / HTTP/1.1 — Host: example.com", severity: "medium" },
    ],
  },
  {
    id: "sess-3",
    src_ip: "192.168.1.10",
    src_port: 53000,
    dst_ip: "8.8.8.8",
    dst_port: 53,
    protocol_guess: "DNS",
    protocol_confidence: 0.9,
    packet_count: 1,
    byte_count: 0,
    is_complete: true,
    completeness_note: null,
    risk: "info",
    summary: "Single outbound DNS query to a public resolver (8.8.8.8). Query contents not decoded.",
    timeline: [
      { time: "12:39:20", label: "DNS query", detail: "192.168.1.10:53000 → 8.8.8.8:53 (UDP)", severity: "neutral" },
    ],
  },
];

export const SAMPLE_FINDINGS = [
  {
    id: "find-1",
    severity: "medium",
    title: "Cleartext HTTP request observed",
    session_id: "sess-2",
    source: "192.168.1.10",
    destination: "93.184.216.34",
    protocol: "HTTP",
    port: 80,
    confidence: 95,
    detail:
      "A plaintext HTTP GET for \"example.com\" was captured on port 80. Any credentials or content on this connection would be visible to anyone on the network path.",
  },
  {
    id: "find-2",
    severity: "low",
    title: "Incomplete TCP capture (port 443)",
    session_id: "sess-1",
    source: "192.168.1.10",
    destination: "93.184.216.34",
    protocol: "TCP",
    port: 443,
    confidence: 100,
    detail:
      "Only the SYN and SYN-ACK were captured. No TLS ClientHello/ServerHello or certificate data is present, so this session cannot be evaluated for TLS version, cipher suite, or certificate validity.",
  },
  {
    id: "find-3",
    severity: "low",
    title: "Incomplete TCP capture (port 80)",
    session_id: "sess-2",
    source: "192.168.1.10",
    destination: "93.184.216.34",
    protocol: "TCP",
    port: 80,
    confidence: 100,
    detail: "No handshake (SYN/SYN-ACK) or teardown (FIN/RST) frames were captured around the HTTP request — the capture window only covers a single mid-stream packet.",
  },
  {
    id: "find-4",
    severity: "info",
    title: "No email-protocol sessions in this capture",
    session_id: null,
    source: "—",
    destination: "—",
    protocol: "SMTP / IMAP / POP3",
    port: null,
    confidence: 100,
    detail: "None of the 3 TCP/UDP streams in this sample matched SMTP, IMAP or POP3 (with or without STARTTLS). This capture is a generic connectivity sample, not mail traffic — upload a capture containing port 25/143/110/465/587/993/995 sessions to exercise the email-analysis pipeline.",
  },
];

export const SAMPLE_STATS = {
  packets_analyzed: SAMPLE_META.packet_count,
  sessions_reconstructed: SAMPLE_SESSIONS.length,
  tls_sessions_seen: 0,
  tls_sessions_complete: 0,
  tls_coverage_pct: 0,
  high_risk_findings: SAMPLE_FINDINGS.filter((f) => f.severity === "high" || f.severity === "critical").length,
  open_investigations: 1,
};
